### ISSUE TITLE
Webgl Build Failed

### ISSUE THREAD

**Issue by haokunABC** [thirdweb-dev/unity-sdk#156]
**Has anyone ever encountered this error? How to fix it, I didn't import or reference other files, just build.**

Building Library\Bee\artifacts\WebGL\build\debug_WebGL_wasm\build.js failed with output:
Traceback (most recent call last):
  File "C:\Program Files\Unity\Hub\Editor\2022.3.17f1c1\Editor\Data\PlaybackEngines\WebGLSupport\BuildTools\Emscripten\emscripten\\emcc.py", line 3982, in <module>
    sys.exit(main(sys.argv))
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\contextlib.py", line 74, in inner
  File "C:\Program Files\Unity\Hub\Editor\2022.3.17f1c1\Editor\Data\PlaybackEngines\WebGLSupport\BuildTools\Emscripten\emscripten\\emcc.py", line 3975, in main
    ret = run(args)
  File "C:\Program Files\Unity\Hub\Editor\2022.3.17f1c1\Editor\Data\PlaybackEngines\WebGLSupport\BuildTools\Emscripten\emscripten\\emcc.py", line 1184, in run
    phase_post_link(options, state, wasm_target, wasm_target, target)
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\contextlib.py", line 74, in inner
  File "C:\Program Files\Unity\Hub\Editor\2022.3.17f1c1\Editor\Data\PlaybackEngines\WebGLSupport\BuildTools\Emscripten\emscripten\\emcc.py", line 2745, in phase_post_link
    phase_emscript(options, in_wasm, wasm_target, memfile)
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\contextlib.py", line 74, in inner
  File "C:\Program Files\Unity\Hub\Editor\2022.3.17f1c1\Editor\Data\PlaybackEngines\WebGLSupport\BuildTools\Emscripten\emscripten\\emcc.py", line 2773, in phase_emscript
    emscripten.run(in_wasm, wasm_target, final_js, memfile)
  File "C:\Program Files\Unity\Hub\Editor\2022.3.17f1c1\Editor\Data\PlaybackEngines\WebGLSupport\BuildTools\Emscripten\emscripten\emscripten.py", line 937, in run
    emscript(in_wasm, out_wasm, outfile_js, memfile)
  File "C:\Program Files\Unity\Hub\Editor\2022.3.17f1c1\Editor\Data\PlaybackEngines\WebGLSupport\BuildTools\Emscripten\emscripten\emscripten.py", line 327, in emscript
    glue, forwarded_data = compile_settings()
  File "C:\Program Files\Unity\Hub\Editor\2022.3.17f1c1\Editor\Data\PlaybackEngines\WebGLSupport\BuildTools\Emscripten\emscripten\emscripten.py", line 183, in compile_settings
    cwd=path_from_root('src'), env=env)
  File "C:\Program Files\Unity\Hub\Editor\2022.3.17f1c1\Editor\Data\PlaybackEngines\WebGLSupport\BuildTools\Emscripten\emscripten\tools\shared.py", line 236, in run_js_tool
    return check_call(command, **kw).stdout
  File "C:\Program Files\Unity\Hub\Editor\2022.3.17f1c1\Editor\Data\PlaybackEngines\WebGLSupport\BuildTools\Emscripten\emscripten\tools\shared.py", line 222, in check_call
    return run_process(cmd, *args, **kw)
  File "C:\Program Files\Unity\Hub\Editor\2022.3.17f1c1\Editor\Data\PlaybackEngines\WebGLSupport\BuildTools\Emscripten\emscripten\tools\shared.py", line 106, in run_process
    ret = subprocess.run(cmd, check=check, input=input, *args, **kw)
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\subprocess.py", line 474, in run
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\subprocess.py", line 926, in communicate
UnicodeDecodeError: 'gbk' codec can't decode byte 0xbd in position 1052008: illegal multibyte sequence

UnityEngine.GUIUtility:ProcessEvent (int,intptr,bool&)

**Comment by 0xFirekeeper** [comment]
Hey @haokunABC 

Assuming you've followed out [Build Settings](https://github.com/thirdweb-dev/unity-sdk?tab=readme-ov-file#general)
`UnicodeDecodeError: 'gbk' codec can't decode byte 0xbd in position 1052008: illegal multibyte sequence` suggests that there are non ascii characters in either your code or filenames, but more likely that you're manipulating bytes / not using UTF8 in some places. 

If that doesn't ring a bell, to debug I would try cloning this repo and building Scene_Prefabs to narrow down whether it's specific to your project or build settings.

**Comment by 0xFirekeeper** [comment]
If you're not manipulating bytes and have things like Japanese characters in some places you can try adding this Editor script, though it may have some side effects.
```
using System;
using UnityEditor.Build;
using UnityEditor.Build.Reporting;

public class WebGLEmscriptenBuildFixer : IPreprocessBuildWithReport
{
    public int callbackOrder => 1;

    public void OnPreprocessBuild(BuildReport report)
    {
        Environment.SetEnvironmentVariable("PYTHONUTF8", "1");
    }
}
```

**Comment by haokunABC** [comment]
Thanks for your answer！**@0xFirekeeper** 
I really didn't work on the project, I just downloaded the project from git, switched platforms, followed the build setup instructions for each step, and I replaced multiple versions of Unity 2022 and two computers that didn't work.

**Comment by haokunABC** [comment]
> If you're not manipulating bytes and have things like Japanese characters in some places you can try adding this Editor script, though it may have some side effects.
> 
> ```
> using System;
> using UnityEditor.Build;
> using UnityEditor.Build.Reporting;
> 
> public class WebGLEmscriptenBuildFixer : IPreprocessBuildWithReport
> {
>     public int callbackOrder => 1;
> 
>     public void OnPreprocessBuild(BuildReport report)
>     {
>         Environment.SetEnvironmentVariable("PYTHONUTF8", "1");
>     }
> }
> ```
This file really worked and I was able to complete the build! However, I encountered an error in the pop-up web page, and the project did not work properly.

The error message is:Uncaught (in promise) ReferenceError: createUnityInstance is not defined
    at

**Comment by haokunABC** [comment]
I solved this problem because the Tuanjie engine I was using was replaced with the previous engine.
